# ── Stage 1: Wheel builder ────────────────────────────────────────────────────
# Downloads all dependencies as binary wheels so the runtime stage
# never needs pip's build cache or a network connection.
FROM python:3.11-slim AS builder

WORKDIR /build

RUN pip install --no-cache-dir --upgrade pip wheel

COPY requirements.txt .
RUN pip wheel --no-cache-dir --wheel-dir=/wheels -r requirements.txt


# ── Stage 2: Runtime ─────────────────────────────────────────────────────────
FROM python:3.11-slim AS runtime

# libgomp1          — TensorFlow CPU parallelism (OpenMP)
# fonts-dejavu-core — matplotlib headless font rendering (Agg backend)
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libgomp1 \
        fonts-dejavu-core \
    && rm -rf /var/lib/apt/lists/*

# Install from pre-built wheels only (no network access required)
COPY --from=builder /wheels /wheels
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --no-index --find-links=/wheels -r /tmp/requirements.txt \
    && rm -rf /wheels /tmp/requirements.txt

# Non-root user with a predictable UID; owns /app so train.py can write output
RUN useradd -m -u 1000 appuser \
    && mkdir -p /app \
    && chown appuser:appuser /app

WORKDIR /app

COPY --chown=appuser:appuser config.py conftest.py test.py train.py ./
COPY --chown=appuser:appuser tests/ ./tests/

# Pre-trained model (~2 MB) — inference works without any volume mounts
# Optional: only copy if it exists
COPY --chown=appuser:appuser digit_model.keras* ./

# Nine bundled PNG samples used for quick demos
COPY --chown=appuser:appuser test_data/ ./test_data/

# train_data/ (~55 MB of .npy arrays) is generated by train.py at runtime;
# mount a host directory here to persist training data and output artifacts.
# Example: -v $(pwd)/train_data:/app/train_data
VOLUME /app/train_data

USER appuser

ENV MPLBACKEND=Agg \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    TF_CPP_MIN_LOG_LEVEL=2

# Default: predict the bundled sample — works with no volume mounts required.
# Override: docker run ... python test.py /data/my_digit.png
#           docker run ... python train.py
#           docker run ... pytest tests/ -v
CMD ["python", "test.py", "test_data/image1.png"]
